### ISSUE TITLE
深翻和复制冲突的问题

### ISSUE THREAD

**Issue by lishoujun** [linuxdeepin/deepin-translator#4]
深翻选中词汇后，会直接弹出翻译框，这时候复制、拖动就会收到影响，建议增加一个固定功能，比如只在任务栏显示翻译结果，或者只在屏幕的指定区域显示结果，用户可以随时拖动这个小窗口并调整其大小。

**Comment by cevarief** [comment]
It keeps translating to chinese, even i set source and target to non chinese. Is there a way to reset or something back to default ?
